[package]
name = "generator"
version = "0.1.0"
authors = ["Simon Brown <si@sjbrown.co.uk>"]
edition = "2018"
publish = false

[dependencies]
heck = "0.4.0"
nom = "7.1.0"
take_mut = "0.2.2"
vk-parse = "0.12"
