[package]
name = "generator"
version = "0.1.0"
authors = ["Simon Brown <si@sjbrown.co.uk>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.79"
heck = "0.4.0"
minreq = { version = "2.11.0", features = ["https"] }
nom = "7.1.0"
take_mut = "0.2.2"
vk-parse = "0.15"
