[package]
name = "compute-lib"
version = "0.1.0"
authors = ["Simon Brown <si@sjbrown.co.uk>"]
edition = "2018"
publish = false

[lib]
crate-type = [ "lib", "cdylib" ]

[dependencies]
spark = { path = "../../spark" }

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = "0.6.1"
