[package]
name = "vkr-imgui"
version = "0.1.0"
authors = ["Simon Brown <si@sjbrown.co.uk>"]
edition = "2018"
publish = false

[dependencies]
vkr = { path = "../vkr" }
imgui = "0.0.22"
arrayvec = "0.4.7"
memoffset = "0.5"
