[package]
name = "spark-imgui"
version = "0.1.0"
authors = ["Simon Brown <si@sjbrown.co.uk>"]
edition = "2018"
publish = false

[dependencies]
spark = { path = "../spark" }
imgui = "0.8.2"
arrayvec = "0.7.2"
memoffset = "0.6.5"
